---
# file: lizardfs.yml
- hosts: lizardfs-client
  user: '{{ user }}'
  sudo: yes
  roles:
    - lizardfs-client

- hosts: lizardfs-master
  user: '{{ user }}'
  sudo: yes
  roles:
    - lizardfs-master

- hosts: lizardfs-chunkserver
  user: '{{ user }}'
  sudo: yes
  roles:
    - lizardfs-chunkserver

- hosts: lizardfs-metalogger
  user: '{{ user }}'
  sudo: yes
  roles:
    - lizardfs-metalogger



