---
# file: site.yml
- hosts: all
  user: '{{ user }}'
  sudo: yes
  vars_files:
    - "vars/common.yml"
    - [ "vars/{{ ansible_os_family }}.yml", "vars/os_defaults.yml" ]

  roles:
    - base

#- include bt-tracker.yml
#- include db-servers.yml
- include: dhcp-servers.yml
#- include dns-servers.yml
#- include domain-controllers.yml
#- include file-servers.yml
- include: loadbalancers.yml
#- include web-servers.yml
