---
# file: site.yml
- hosts: all
  user: '{{ deploy_user }}'
  become: true
  vars_files:
    - "vars/common.yml"
    - [ "vars/{{ansible_os_family}}.yml", "vars/common.yml" ]

  roles:
    - base

#- include: web-servers.yml
#- include: lizardfs.yml
#- include: bt-tracker.yml
#- include: db-servers.yml
#- include: dhcp-servers.yml
#- include: dns-servers.yml
#- include: domain-controllers.yml
#- include: file-servers.yml
#- include: loadbalancers.yml
