---
# name: Install and configure basic settings on a host.
- debug: msg="Testing {{ansible_distribution}} {{ansible_distribution_version}} {{ansible_distribution_release}}"

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: debian.yml
  when: ansible_distribution == 'Debian'

# Ubuntu/Debian are the same for this role.
- include: debian.yml
  when: ansible_distribution == 'Ubuntu'
