---
# name: Install and configure a LizardFS Master/metadata server

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: debian.yml
  when: ansible_distribution == 'Debian'

# Ubuntu/Debian are the same for this role.
- include: debian.yml
  when: ansible_distribution == 'Ubuntu'
