---
# name: Install and configure LizardFS on a host on Debian 7/Ubuntu

- name: Apt - Add apt-key for LizardFS developers
  apt_key: url="http://packages.lizardfs.com/lizardfs.key" state=present

- name: Apt - Add apt repository for LizardFS
  apt_repository: repo='deb http://packages.lizardfs.com/{{ansible_distribution | lower}}/{{ansible_distribution_release}} {{ansible_distribution_release}} main' state=present
  notify:
  - update apt cache

- name: Apt - Install LizardFS chunkserver
  apt: name=lizardfs-chunkserver state=installed

- name: Defaults - Enable LizardFS chunkserver
  lineinfile: 'dest=/etc/default/lizardfs-chunkserver regexp=^LIZARDFSCHUNKSERVER_ENABLE line="LIZARDFSCHUNKSERVER_ENABLE=true"'

- name: File - Create brick folder
  file: path=/mnt/bricks/local state=directory mode=0755 owner=mfs group=mfs

- name: LFS - Add configuration file.
  template: src=mfschunkserver.cfg.j2 dest=/etc/mfs/mfschunkserver.cfg mode=0640

- name: LFS - Add HDD mounts file.
  template: src=mfshdd.cfg.j2 dest=/etc/mfs/mfshdd.cfg mode=0640

- name: Service - Start LizardFS chunkserver
  service: name=lizardfs-chunkserver state=started

#
# bennojoy  Gnomethrower: i would think writing a custom model would be better here, but what you could do is soemthink like shell: ls -l /mnt/mbricks/ register: foo
# bennojoy  and the use foo.stdout_lines
